# Titanic

In [79]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [80]:
data = pd.read_csv('train.csv')
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## Limpieza de datos

Lo primero es ver la cantidad de datos nulos para ver si hay que eliminar alguna columna

In [81]:
# Cantidad de nulos por columna
nulos = data.isna().sum()
nulos

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Ahora hay que ver que porcentaje de nulos hay en cada columna

In [82]:
#total de elementos en cada columna, considerando los nulos
total = data.isna().count()    

#nulos dividido el total, multiplicado por 100 para obtener el porcentaje
porcentaje = (nulos / total) * 100      

#concatenamos los nulos y el porcentaje en un nuevo dataframe llamado datos_faltantes, con las columnas 'Nulos' y 'Porcentaje'
datos_faltantes = pd.concat([nulos, porcentaje], axis=1, keys=['Nulos', 'Porcentaje'])  

datos_faltantes

             Nulos  Porcentaje
PassengerId      0    0.000000
Survived         0    0.000000
Pclass           0    0.000000
Name             0    0.000000
Sex              0    0.000000
Age            177   19.865320
SibSp            0    0.000000
Parch            0    0.000000
Ticket           0    0.000000
Fare             0    0.000000
Cabin          687   77.104377
Embarked         2    0.224467

Se eliminara la columna Cabin ya que su porcentaje de datos nulos es de un 77%

In [83]:
data = data.drop('Cabin', axis=1)
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

Como hay dos datos nulos en la Columna Embarked, simplemente se eliminan esas dos filas

In [84]:
data = data.dropna(subset=['Embarked'])
nulos = data.isna().sum()
nulos

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         0
dtype: int64

Rellenar los datos de la columna Age con cero

In [85]:
#primero ver el valor maximo y minimo de la columna Age
edad_maxima = data['Age'].max()
edad_minima = data['Age'].min()

print(f'Edad maxima: {edad_maxima}, Edad minima: {edad_minima}')

#rellenar con 0
data['Age'] =data['Age'].fillna(0)
data

Edad maxima: 80.0, Edad minima: 0.42

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,0.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

## Analisis exploratorio